use quay.io/centos/centos:stream8 as CentOS 8 base image
because of the following error at "yum -y install":

    Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist